services:
  - type: web
    name: crm-barber-frontend
    env: static
    buildCommand: |
      npm install &&
      npm run build
    staticPublishPath: /opt/render/project/src/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://crm-barber-backend.onrender.com/api
      - key: REACT_APP_SOCKET_URL
        value: https://crm-barber-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-cache 