services:
  - type: web
    name: crm-barber
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd backend && npm install && chmod +x build.sh && ./build.sh && cd ..
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # This will be set in Render's dashboard
      - key: JWT_SECRET
        sync: false # This will be set in Render's dashboard 