services:
  - type: web
    name: crm-barber-backend
    env: node
    region: oregon
    plan: free
    buildCommand: |
      cd backend && 
      npm install &&
      echo "Current directory: $(pwd)" &&
      echo "TypeScript version: $(npx tsc --version)" &&
      npm run build &&
      echo "Running Prisma migrations..." &&
      npx prisma migrate deploy &&
      echo "Running seeds..." &&
      node dist/prisma/seeds/categories.js &&
      node dist/prisma/seeds/barber.js &&
      echo "Build process completed successfully"
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # This will be set in Render's dashboard
      - key: JWT_SECRET
        sync: false # This will be set in Render's dashboard 