services:
  - type: web
    name: crm-barber
    env: node
    region: oregon
    plan: free
    buildCommand: |
      cd backend && 
      npm install &&
      npm run build &&
      ls -la dist/
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # This will be set in Render's dashboard
      - key: JWT_SECRET
        sync: false # This will be set in Render's dashboard 